use crate::{SliderState, convert_to_shadertoy};
use bevy::math::Vec4;
use std::path::PathBuf;

#[test]
fn test_simple_shader_conversion() {
    let shader_content = r#"
#version 450
layout(location = 0) in vec2 uv;
layout(location = 0) out vec4 fragColor;

layout(set = 2, binding = 0) uniform float iTime;
layout(set = 2, binding = 1) uniform vec2 iResolution;

void main() {
    fragColor = vec4(uv, 0.5, 1.0);
}
    "#;

    let slider_state = SliderState {
        sliders_1: Vec4::new(1.0, 0.5, 0.25, 0.0),
        sliders_2: Vec4::new(0.0, 0.0, 0.0, 0.0),
        sliders_3: Vec4::new(0.0, 0.0, 0.0, 0.0),
        sliders_4: Vec4::new(0.0, 0.0, 0.0, 0.0),
        sliders_5: Vec4::new(0.0, 0.0, 0.0, 0.0),
    };

    let shader_path = PathBuf::from("test.frag");
    let result = convert_to_shadertoy(shader_content, &slider_state, &shader_path);

    // Check that the result contains expected elements
    assert!(result.contains("// Generated by bevy_shader_runner shadertoy dump"));
    assert!(result.contains("// Original shader: test.frag"));
    assert!(result.contains("void mainImage(out vec4 fragColor, in vec2 fragCoord)"));
    assert!(result.contains("vec2 uv = fragCoord / iResolution.xy;"));
    assert!(result.contains("const vec4 slider1 = vec4(1, 0.5, 0.25, 0)"));
    assert!(result.contains("const vec4 slider2 = vec4(0, 0, 0, 0)"));

    // Check that unwanted elements are removed
    assert!(!result.contains("#version 450"));
    assert!(!result.contains("layout(location = 0) in vec2 uv;"));
    assert!(!result.contains("layout(location = 0) out vec4 fragColor;"));
    assert!(!result.contains("layout(set = 2, binding = 0) uniform float iTime;"));
    assert!(!result.contains("layout(set = 2, binding = 1) uniform vec2 iResolution;"));
    assert!(!result.contains("layout(set = 2, binding = 2) uniform vec4 slider1;"));
    assert!(!result.contains("void main() {"));
}

#[test]
fn test_shader_with_functions() {
    let shader_content = r#"
#version 450
layout(location = 0) in vec2 uv;
layout(location = 0) out vec4 fragColor;

layout(set = 2, binding = 0) uniform float iTime;
layout(set = 2, binding = 1) uniform vec2 iResolution;

vec3 hsv2rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

void main() {
    vec3 color = hsv2rgb(vec3(uv.x, 1.0, 1.0));
    fragColor = vec4(color, 1.0);
}
    "#;

    let slider_state = SliderState::default();
    let shader_path = PathBuf::from("test.frag");
    let result = convert_to_shadertoy(shader_content, &slider_state, &shader_path);

    // Check that helper functions are preserved
    assert!(result.contains("vec3 hsv2rgb(vec3 c) {"));
    assert!(result.contains("vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);"));

    // Check that the function call is preserved in the main function
    assert!(result.contains("vec3 color = hsv2rgb(vec3(uv.x, 1.0, 1.0));"));
}

#[test]
fn test_all_sliders_conversion() {
    let shader_content = r#"
#version 450
layout(location = 0) in vec2 uv;
layout(location = 0) out vec4 fragColor;

layout(set = 2, binding = 0) uniform float iTime;
layout(set = 2, binding = 1) uniform vec2 iResolution;
layout(set = 2, binding = 2) uniform vec4 slider1;
layout(set = 2, binding = 3) uniform vec4 slider2;
layout(set = 2, binding = 4) uniform vec4 slider3;
layout(set = 2, binding = 5) uniform vec4 slider4;
layout(set = 2, binding = 6) uniform vec4 slider5;

void main() {
    fragColor = vec4(slider1.x, slider2.y, slider3.z, slider4.w + slider5.x);
}
    "#;

    let slider_state = SliderState {
        sliders_1: Vec4::new(0.1, 0.2, 0.3, 0.4),
        sliders_2: Vec4::new(0.2, 0.3, 0.4, 0.5),
        sliders_3: Vec4::new(0.3, 0.4, 0.5, 0.6),
        sliders_4: Vec4::new(0.4, 0.5, 0.6, 0.7),
        sliders_5: Vec4::new(0.5, 0.6, 0.7, 0.8),
    };

    let shader_path = PathBuf::from("test.frag");
    let result = convert_to_shadertoy(shader_content, &slider_state, &shader_path);

    // Check that all sliders are converted to constants
    assert!(result.contains("const vec4 slider1 = vec4(0.1, 0.2, 0.3, 0.4)"));
    assert!(result.contains("const vec4 slider2 = vec4(0.2, 0.3, 0.4, 0.5)"));
    assert!(result.contains("const vec4 slider3 = vec4(0.3, 0.4, 0.5, 0.6)"));
    assert!(result.contains("const vec4 slider4 = vec4(0.4, 0.5, 0.6, 0.7)"));
    assert!(result.contains("const vec4 slider5 = vec4(0.5, 0.6, 0.7, 0.8)"));

    // Check that slider usage is preserved
    assert!(
        result
            .contains("fragColor = vec4(slider1.x, slider2.y, slider3.z, slider4.w + slider5.x);")
    );
}

#[test]
fn test_complex_shader_structure() {
    let shader_content = r#"
#version 450
layout(location = 0) in vec2 uv;
layout(location = 0) out vec4 fragColor;

layout(set = 2, binding = 0) uniform float iTime;
layout(set = 2, binding = 1) uniform vec2 iResolution;

// Noise functions
float hash(float n) { return fract(sin(n) * 1e4); }
float noise(vec2 x) {
    vec2 p = floor(x);
    vec2 f = fract(x);
    f = f * f * (3.0 - 2.0 * f);
    float n = p.x + p.y * 57.0;
    return mix(mix(hash(n + 0.0), hash(n + 1.0), f.x),
               mix(hash(n + 57.0), hash(n + 58.0), f.x), f.y);
}

void main() {
    float n = noise(uv * 10.0 + iTime);
    vec3 col = vec3(n);
    fragColor = vec4(col, 1.0);
}
    "#;

    let slider_state = SliderState::default();
    let shader_path = PathBuf::from("test.frag");
    let result = convert_to_shadertoy(shader_content, &slider_state, &shader_path);

    // Check that complex structures are preserved
    assert!(result.contains("float hash(float n) { return fract(sin(n) * 1e4); }"));
    assert!(result.contains("float noise(vec2 x) {"));
    assert!(result.contains("vec2 p = floor(x);"));
    assert!(result.contains("float n = noise(uv * 10.0 + iTime);"));
}

#[test]
fn test_shadertoy_main_function_conversion() {
    let shader_content = r#"
#version 450
layout(location = 0) in vec2 uv;
layout(location = 0) out vec4 fragColor;

layout(set = 2, binding = 0) uniform float iTime;
layout(set = 2, binding = 1) uniform vec2 iResolution;

void main() {
    // Complex main function
    vec2 center = vec2(0.5) - uv;
    float dist = length(center);
    float angle = atan(center.y, center.x);
    vec3 color = 0.5 + 0.5 * cos(vec3(angle, angle + 2.0, angle + 4.0));
    color *= 1.0 - smoothstep(0.4, 0.5, dist);
    fragColor = vec4(color, 1.0);
}
    "#;

    let slider_state = SliderState::default();
    let shader_path = PathBuf::from("test.frag");
    let result = convert_to_shadertoy(shader_content, &slider_state, &shader_path);

    // Check that the main function is properly converted
    assert!(result.contains("void mainImage(out vec4 fragColor, in vec2 fragCoord) {"));
    assert!(result.contains("vec2 uv = fragCoord / iResolution.xy;"));

    // Check that the main function body is preserved (with proper indentation)
    assert!(result.contains("vec2 center = vec2(0.5) - uv;"));
    assert!(result.contains("float dist = length(center);"));
    assert!(result.contains("float angle = atan(center.y, center.x);"));
    assert!(
        result.contains("vec3 color = 0.5 + 0.5 * cos(vec3(angle, angle + 2.0, angle + 4.0));")
    );
    assert!(result.contains("color *= 1.0 - smoothstep(0.4, 0.5, dist);"));
    assert!(result.contains("fragColor = vec4(color, 1.0);"));
}
